# Generated by Django 5.0.4 on 2024-04-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folk', '0003_alter_lesson_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parsing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Useful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('text', models.TextField()),
            ],
        ),
    ]
