# Generated by Django 5.0.4 on 2024-04-19 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folk', '0006_rename_image_imageholder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageHolder',
            new_name='Image',
        ),
    ]
