# Generated by Django 5.0.4 on 2024-04-20 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folk', '0014_rename_message_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='body',
        ),
    ]
