# Generated by Django 5.0.4 on 2024-06-03 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folk', '0016_lesson_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='useful',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='folk.useful'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useful',
            name='image',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
