# Generated by Django 5.0.4 on 2024-06-03 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folk', '0018_commentuseful'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentUseful',
        ),
    ]
