# Generated by Django 5.0.4 on 2024-06-03 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folk', '0020_commentuseful'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='useful',
        ),
    ]
